# Generated by Django 3.2.8 on 2021-10-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_listing_bids_listing_bid_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listings',
        ),
    ]
