# Generated by Django 3.2.8 on 2021-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bids_listing_bid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listings',
            field=models.ManyToManyField(to='auctions.AuctionListings'),
        ),
    ]
