# Generated by Django 3.2.8 on 2021-10-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211021_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='starting_bid',
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listings',
        ),
        migrations.AddField(
            model_name='bids',
            name='listings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
    ]
