# Generated by Django 3.2.8 on 2021-10-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211021_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
    ]
