# Generated by Django 3.2.8 on 2021-10-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlistings_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
