# Generated by Django 3.2.8 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlistings_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Shoe', 'Shoe'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Miscellaneous', 'Miscellaneous'), ('Kitchen', 'Kitchen'), ('None', 'None')], max_length=30),
        ),
    ]
