# Generated by Django 3.2.8 on 2021-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Miscellaneous', 'Miscellaneous'), ('None', 'None')], max_length=20),
        ),
    ]
